[build]
  command = "npm run build" # Replace with your actual build command
  publish = "build" # Replace with the directory where your built files are located
  timeout = 1800 # 30 minutes in seconds